Add algorithm selection for training/importing
spiceai/spiceai pull request #328
Opened 2021-10-19 04:07 UTC by Corentin-pro

I haven't check the test yet but I think this is a good base to see the direction of this feature and discuss. Everything is working from my manual tests but I might missed some things.

Resolves #327 

Summary of the commit :
* Add 'algorithm' key in aiengine protos (StartTrainingRequest, ImportModelRequest)
* Add 'algorithm' key in runtime protos (TrainModel, ImportModel)
* Clean code (PEP8, flake) for ai scripts : main.py and train.py
* Reduce Tensorflow verbose before import to avoid unecessary info logs
  (main.py l.318)
* Add 'algorithm' flag for import and train command (CLI)

2021-10-19 04:58 UTC, lukekim requested changes

2021-10-19 04:58 UTC, lukekim commented on ai/src/algorithms/factory.py
>      raise NotImplementedError(f"Unable to find agent with name '{name}'")
Maybe we should update this error message to refer to learning-algorithm?

2021-10-19 04:58 UTC, lukekim commented on pkg/cli/cmd/train.go
> +			Algorithm: algorithmFlag,
As we want to be developer friendly as possible, let's call this `LearningAlgorithm` and in json `learning_algorithm` because many developers will not understand what this algorithm refers to.

2021-10-19 04:58 UTC, lukekim commented on pkg/cli/cmd/train.go
> +	trainCmd.Flags().StringVar(&algorithmFlag, "algorithm", "", "Train the pod with specified algorithm")
same comment as above, many users won't know what algorithm refers to, so let's use `learning-algorithm`

2021-10-19 04:58 UTC, lukekim commented on pkg/cli/cmd/import.go
> +	ImportCmd.Flags().StringVar(&algorithmTag, "algorithm", "dql", "Specify algorithm of the pod")
```suggestion
	ImportCmd.Flags().StringVar(&algorithmTag, "learning-algorithm", "dql", "Specify the AI engine learning algorithm")
```

2021-10-19 04:59 UTC, lukekim commented
Nice work! You'll also need to update the `.github/worflows/e2e.yaml` with the algorithm change.

2021-10-20 09:32 UTC, Corentin-pro commented on ai/src/algorithms/factory.py
>      raise NotImplementedError(f"Unable to find agent with name '{name}'")
The message has been update.

2021-10-20 09:37 UTC, Corentin-pro commented
@phillipleblanc I made the change to pass all the e2e test, I do not understand the pr_test well (`go test -v ./... -shuffle=on`). I feel I will need some guidance to fix it.

2021-10-20 10:00 UTC, phillipleblanc commented
> @phillipleblanc I made the change to pass all the e2e test, I do not understand the pr_test well (`go test -v ./... -shuffle=on`). I feel I will need some guidance to fix it.

Looks like this change will fix the Go unit tests.

<img width="764" alt="Screen Shot 2021-10-20 at 6 51 57 PM" src="https://user-images.githubusercontent.com/879445/138072575-8236d60a-21bd-431a-a800-540bb5ecc64f.png">

2021-10-20 10:25 UTC, Corentin-pro commented
Now every test is OK!

The new feature works as follow :

- '--learning-algorithm' can be used with the `train` command of the CLI (like `spice train [pod] --learning-algorithm [dql|vpg]`)
- a pod can specify a default learning_algorithm in its yaml (I need to check this more, I don't think there is a test for that)
- to avoid problem with import/export (I made the same flag there at first but eventually this was not a good solution) the model is now saved as a folder with a `meta.json` with meta data and `model.pb`. For now the meta data only consist of `algorithm` and 'model_name' (storing `model.pb`, could change latter).

As a side note I changed the temporary folder creation by adding a prefix (the python function that create the temporary folder had the parameter but was unused) to start with `spiceai_`. In case of crashes/wrong cleanup this is easier to clean manually and cleaner overall.

2021-10-20 10:27 UTC, Corentin-pro commented on pkg/cli/cmd/train.go
> +			Algorithm: algorithmFlag,
Agreed, I changed all occurrences in APIs/CLI flags to `learning_algorithm`. Only short lived local variables remains with the name `algorithm` and the meta data of the model.

2021-10-20 10:32 UTC, phillipleblanc submitted a review, later dismissed
Awesome first PR! Thanks for working through those test issues.

2021-10-20 11:13 UTC, lukekim submitted a review, later dismissed

2021-10-20 11:13 UTC, lukekim commented on pkg/pods/podparams.go
> +		Algorithm: "dql",
Looks like you might need to run `gofmt -w -s -l .`

2021-10-20 11:13 UTC, lukekim commented on ai/src/Makefile
> +	ALGORITHM="dql" venv/bin/python3 -m pytest --timeout 10
One reason to prefix with `SPICE_` is the environment variable can be used in the manifest, as the config will auto-replace anything with that prefix.

2021-10-20 11:32 UTC, Corentin-pro commented on pkg/pods/podparams.go
> +		Algorithm: "dql",
Indeed, I pushed a commit fixing this, next time I will set up my IDE to format on save.

2021-10-20 11:35 UTC, Corentin-pro commented on ai/src/Makefile
> +	ALGORITHM="dql" venv/bin/python3 -m pytest --timeout 10
OK, I didn't know that, the good thing is that this environment variable is exclusively used for pytest as I couldn't figured out yet how to parameterize the testing (without a lot of changes).

A solution here would be to prefix with 'TEST_' to explicit the nature of this environment variable.

2021-10-20 11:55 UTC, lukekim approved these changes

2021-10-20 11:55 UTC, phillipleblanc approved these changes

2021-10-20 12:17 UTC, merged