CLI command to list currently loaded pods from runtime
spiceai/spiceai pull request #334
Opened 2021-10-21 06:18 UTC by sboorlagadda

1) spice shows pods as a command

```bash
❯ ./spice
Spice.ai CLI

Usage:
  spice [command]

Available Commands:
  action      Maintains actions
  add         Add Pod - adds a pod to the project
  completion  generate the autocompletion script for the specified shell
  export      Export Pod - export a pod
  help        Help about any command
  import      Import Pod - import a pod
  init        Initialize Pod - initializes a new pod in the project
  pods        Retrieve pods
  reward      Maintains rewards
  run         Run Spice.ai - starts the Spice.ai runtime, installing if necessary
  train       Train Pod - start a pod training run
  upgrade     Upgrades Spice.ai runtime if necessary
  version     Spice CLI version

Flags:
  -h, --help   help for spice

Use "spice [command] --help" for more information about a command.
```
2) `spice pods -h` shows a help

```bash
❯ ./spice pods -h
Retrieve pods

Usage:
  spice pods [command]

Aliases:
  pods, pods

Examples:

spice pods list

Available Commands:
  list        Lists available pods in the runtime

Flags:
  -h, --help   Prints this help message

Use "spice pods [command] --help" for more information about a command.

```
3) `spice pods list -h` shows a help
```bash
❯ ./spice pods list -h
Lists available pods in the runtime

Usage:
  spice pods list [flags]

Examples:

spice pods list

Flags:
  -h, --help   Prints this help message
  
```
4) This is how the command lists the output
```bash  
  ❯ ./spice pods list
  NAME              MANIFEST PATH
  customprocessor   /userapp/spicepods/customprocessor.yaml
  event-categories  /userapp/spicepods/event-categories.yaml
  event-tags        /userapp/spicepods/event-tags.yaml
  trader            /userapp/spicepods/trader.yaml
```

5) if the runtime not running
```bash
❯ ./spice pods list
failed to reach http://localhost:8000. is the spice runtime running?
```

Closes #333

2021-10-21 06:19 UTC, sboorlagadda commented on pkg/cli/cli_test.go
> +		output, err := executeCommand(root, "pods", "list")
@lukekim @phillipleblanc How can I add pods so I can add a test?

2021-10-21 06:32 UTC, sboorlagadda commented on pkg/cli/cli_test.go
> +		output, err := executeCommand(root, "pods", "list")
I probably can `run` first in `spicepods/foo.yaml`

2021-10-21 06:33 UTC, lukekim requested changes
Awesome start, thanks @sboorlagadda !

2021-10-21 06:33 UTC, lukekim commented on pkg/cli/cli_test.go
> +	t.Run("podListCmd() - spice pod list list available pods", testPodListCmd(cmd.RootCmd))
```suggestion
	t.Run("podListCmd() - spice pod list lists loaded pods", testPodListCmd(cmd.RootCmd))
```

2021-10-21 06:33 UTC, lukekim commented on pkg/cli/cli_test.go
> +// Tests pod list lists all availalbe pods
```suggestion
// Tests pod list lists currently loaded pods
```

2021-10-21 06:33 UTC, lukekim commented on pkg/cli/cli_test.go
> +		output, err := executeCommand(root, "pods", "list")
This should probably actually be part of the e2e tests under `test/e2e` as it tests CLI + Runtime interaction. You can see examples in that, where the runtime and pods are loaded.

2021-10-21 06:33 UTC, lukekim commented on pkg/cli/cli_test.go
> +		output, err := executeCommand(root, "pods", "list")
If you wanted to also add a test here, you would need to mock the HTTP call to the runtime.

2021-10-21 06:33 UTC, lukekim commented on pkg/cli/cmd/pods.go
> +		fmt.Fprintf(w, "%s\t%s\n", "Pod Name", "Manifest")
I'd replace this with `"github.com/gocarina/gocsv"` + `"github.com/olekukonko/tablewriter"`. Then you can handle variable widths with `gocsv.MarshalString`. Check out an example here: https://github.com/dapr/cli/blob/f92eebacc6c5530e326e96b9f6bc49f7cafff58b/utils/utils.go#L35

2021-10-25 01:23 UTC, sboorlagadda commented on test/e2e/cli.go
> +func (c *cli) runCliCmdOutput(args ...string) ([]byte, error) {
@lukekim Do you suggest a better name for the func?

2021-10-25 01:36 UTC, phillipleblanc approved these changes

2021-10-25 02:49 UTC, lukekim approved these changes

2021-10-25 02:49 UTC, lukekim commented on test/e2e/cli.go
> +func (c *cli) runCliCmdOutput(args ...string) ([]byte, error) {
Fine for now!

2021-10-25 02:50 UTC, merged