Add dremio authorization by calling apiv2/login
spiceai/spiceai pull request #682
Opened 2024-02-14 19:56 UTC by Sevenannn

Call dremio http://{hostname}/apiv2/login endpoint to verify username and password when user call `spice login dremio`

2024-02-21 03:44 UTC, phillipleblanc commented on bin/spice/pkg/cli/cmd/login.go
> +	const dremioHost = "dremio-4mimamg7rdeve.eastus.cloudapp.azure.com:9047"
Let's remove this hard-coding, ref: https://github.com/spicehq/spiceai/issues/100

2024-02-22 01:22 UTC, phillipleblanc requested changes
We decided not to put this into the current release

2024-02-22 22:38 UTC, lukekim commented on bin/spice/pkg/cli/cmd/login.go
> +		UserName string `json:"userName"`
Weird casing. Don't capitalize N.

2024-02-22 22:38 UTC, lukekim commented on bin/spice/pkg/cli/cmd/login.go
> +			cmd.Println("Invalid dremio username or password")
Capital D for Dremio.

2024-02-22 22:38 UTC, lukekim commented on bin/spice/pkg/cli/cmd/login.go
> +			cmd.Println("Invalid dremio username or password")
Actually, just remove the word Dremio altogether.

2024-02-22 22:39 UTC, lukekim commented on bin/spice/pkg/cli/cmd/login.go
> +	dremioLoginAddr := fmt.Sprintf("http://%s/apiv2/login", dremioHost)
This should use https if supported.

2024-02-22 22:39 UTC, lukekim commented on bin/spice/pkg/cli/cmd/login.go
> +	jsonData, err := json.Marshal(creds)
This won't work without attributes on the struct.

2024-02-22 22:40 UTC, lukekim commented on bin/spice/pkg/cli/cmd/login.go
> +	req.Header.SetContentType("application/json")
Do we not have a help for a JSON request?

2024-02-22 22:41 UTC, lukekim commented on bin/spice/pkg/cli/cmd/login.go
> +	return false
Don't return a bool. Align to Go conventions. Return an error if it fails and nil if it succeeds. or both a bool and error.

2024-02-23 03:30 UTC, closed without merging