Change dremio login to spice login dremio-cloud
spiceai/spiceai pull request #686
Opened 2024-02-14 22:23 UTC by Sevenannn

2024-02-16 05:28 UTC, sgrebnov approved these changes

2024-02-16 05:53 UTC, phillipleblanc commented on bin/spice/pkg/cli/cmd/login.go
> +spice login dremio-cloud --username <username> --password <password>
We'll also need to change the data connector selector in the Rust project

2024-02-22 19:48 UTC, digadeesh requested changes
Let's hold on this for now.  We're having some discussions on the namespacing and we'd have to update our spicepods again with this namespace change.  Better to make a clear decision on where it should all go and then make the changes.

2024-02-22 22:42 UTC, lukekim commented
I think we decided against this rename and will keep Dremio for now. Closing.

2024-02-22 22:42 UTC, closed without merging