Add `v1/status`.
spiceai/spiceai pull request #802
Opened 2024-03-13 11:31 UTC by Jeadie

2024-03-13 18:45 UTC, lukekim commented on crates/runtime/src/http/v1.rs
> +        Yaml,
Let's scope support to just JSON and CSV.

2024-03-13 18:46 UTC, lukekim submitted a review, later dismissed

2024-03-14 02:16 UTC, Jeadie commented
Not implementing for opentelemetry collector as it doesn't satisfies GRPC [health checks](https://grpc.io/docs/guides/health-checking/)

2024-03-14 15:29 UTC, mitchdevenport requested changes
I'm not sure that adding a basic health service is as much work as you're thinking it is. All we need to do is use the pre-compiled protos provided by tonic, attach the service to the same tonic server, and implement a very basic health check. Since we just want to know that the server is up, it could probably just always return `Ok`.

2024-03-15 00:43 UTC, sgrebnov approved these changes, later dismissed

2024-03-15 00:48 UTC, ewgenius approved these changes

2024-03-15 00:50 UTC, mitchdevenport approved these changes

2024-03-15 00:50 UTC, merged